### PR TITLE
Built user authentication.

### PR DESCRIPTION
**Pull request by Anonymous-Stranger**
:confetti_ball: :sunglasses: :confetti_ball:

### CODE REVIEW

**Review by ByronBecker — COMMENTED** [review]
Great formatting, it makes the code super readable.

In the wrapper function:
     Just looked up *args, **kwargs, what would the    
     variable parameters passed in here represent?

In the create_user function, maybe return "This Username is Already Taken" instead of "Duplicate Username". Also for now its fine to know if its the password or username that's incorrect, but maybe eventually we just respond with "the username or password entered is invalid" to not give anything away.

In the changes to newUser.py, will each of us only have access to our specific login information upon using the app on the client side? I guess my question is does this make it much harder to curl different people and insert randomly while testing? If so, maybe we hold off until all other features have been implemented.

**Comment by ByronBecker** [comment]
Just one thing you might want to pull the most recent copy and add that to the pull request, I submitted some changes in the most recent merge in adding an appTotal Function that updates all of the totals in the db, that I didn't see in your pull request. Also, I see that you put the weekly and goals variables into the globalopts (default) file, I like that!

**Comment by Anonymous-Stranger** [comment]
Oh shoot, sorry about that. Let me do that right now.

**Comment by Anonymous-Stranger** [comment]
So the new newUser.py is NOT in the root directory. It's moved to its own folder called focus_server.

**Comment by ByronBecker** [comment]
Ah, ok I see now! Looks good Akash 👍

**Comment by Anonymous-Stranger** [comment]
Oh also, I forgot to answer these questions:


Q: Just looked up *args, **kwargs, what would the variable parameters passed in here represent?
A: Args and kwargs are used to forward any possible parameters to the function being modified. This is because we don't know what arguments the function being modified takes.


Q-ish: In the create_user function, maybe return "This Username is Already Taken" instead of "Duplicate Username". 
A: Same difference, feel free to change it to whatever. Remember that short concise messages are better than long ones, and that all errors should be formatted the same (eg, all lowercase, or all properly capitalized, etc.)


Q-ish: Also for now its fine to know if its the password or username that's incorrect, but maybe eventually we just respond with "the username or password entered is invalid" to not give anything away. 
A: We don't give anything away -- this is user creation, not user login. User login does exactly what you said, responding with a login failed and a 401 (I think? Otherwise a 400). However, this isn't useful when the person is creating an account, since not giving information is to prevent someone else from logging in.


Q: In the changes to newUser.py, will each of us only have access to our specific login information upon using the app on the client side? I guess my question is does this make it much harder to curl different people and insert randomly while testing? If so, maybe we hold off until all other features have been implemented.
A: As long as you know the username and password, it's simple, just login as them to get their authorization token, and then use that with your requests. If you want to be someone else, just use their auth token.


Also, side note, to log out, just delete the auth token and return to the login page. In our app, we would want to just store the token until they log out, because we'll need it for when they update usage data.

**Comment by ByronBecker** [comment]
👍  Merge when ready

**Pull request merged**
