### PR TITLE
Slight change to mission statement.

### PR DESCRIPTION
**Pull request by Anonymous-Stranger**
I wasn't sure if the original was entirely a vision statement, so I tried to adjust it without changing the meaning and intent. If you guys have something you don't like, or improvements, please suggest changes.

### CODE REVIEW

**Comment by ByronBecker** [comment]
I'm thinking maybe "Helping every person to better manage their schedule, one second at a time"

**Comment by Anonymous-Stranger** [comment]
How about get rid of "to better"?

**Comment by ByronBecker** [comment]
Sounds good to me

**Comment by ByronBecker** [comment]
How did you link this to slack?

**Pull request merged**
